# Configurações comuns
spring.application.name=voltic
server.port=8080

# Configurações da aplicação personalizada
app.user.username=root
app.user.password=root

# Connection string para Azure IoT Hub
azure.iothub.connection-string=${AZURE_IOTHUB_CONNECTION_STRING}

# Conexão com o MongoDB (Cosmos DB via API Mongo)
spring.data.mongodb.uri=${SPRING_DATA_MONGODB_URI}
spring.data.mongodb.database=cosmos-voltic-db

# Configurações do JWT
app.jwt.secret=B3EzPGnI2tOzcrZ+I3OyskI8EoJi7EzhzoYGi2vWjps=
app.jwt.expiration=7200000

# Debug
logging.level.org.springframework=DEBUG
logging.level.org.hibernate.SQL=DEBUG

management.endpoints.web.exposure.include=health,info
management.health.mongo.enabled=false
